// MOVIES
export const GET_NOW_PLAYING_MOVIES = 'GET_NOW_PLAYING_MOVIES';
export const GET_POPULAR_MOVIES = 'GET_POPULAR_MOVIES';
export const GET_UPCOMING_MOVIES = 'GET_UPCOMING_MOVIES';
export const GET_TOP_RATED_MOVIES = 'GET_TOP_RATED_MOVIES';

// SERIES

export const GET_ON_THE_AIR_SERIES = 'GET_ON_THE_AIR_SERIES';
export const GET_UPCOMING_SERIES = 'GET_UPCOMING_SERIES';
export const GET_POPULAR_SERIES = 'GET_POPULAR_SERIES';
export const GET_TOP_RATED_SERIES = 'GET_TOP_RATED_SERIES';